name: Vaibhav Bhanot
favicon: null
layout_spectrum: 1
typography_spectrum: 0.69225
title: Design Experience Innovation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#36c391'
    - '#ff7600'
    - '#979797'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
