name: Vaibhav Bhanot
favicon: null
layout_spectrum: 1
typography_spectrum: 0.69225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#fedf15'
    - '#818286'
    - '#c7c7c7'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
